# Generated by Django 4.0.1 on 2022-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name_plural': '마켓'},
        ),
    ]
