# Generated by Django 4.0.1 on 2022-01-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clothes', to='clothes.categories', verbose_name='카테고리')),
                ('colors', models.ManyToManyField(blank=True, related_name='clothes', to='options.Color', verbose_name='색상')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('file', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='clothes.clothes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
