# Generated by Django 4.0.1 on 2022-01-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('options', '0001_initial'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL, verbose_name='판매자'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='markets.market', verbose_name='사이트'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='clothes', to='options.Size', verbose_name='사이즈'),
        ),
    ]
