# Generated by Django 4.0.1 on 2022-01-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': '상품'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': '상품 사진'},
        ),
    ]
