# Generated by Django 4.0.1 on 2022-03-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_categories_options_alter_clothes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clothes', to='clothes.categories', verbose_name='카테고리'),
        ),
    ]
